pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - "status-success=ci/circleci: build"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
        strict: true
